# Generated by Django 4.1.1 on 2022-11-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technology', 'TECHNOLOGY'), ('lifestyle', 'LIFESTYLE'), ('fashion', 'FASHION'), ('art', 'ART'), ('food', 'FOOD'), ('travel', 'TRAVEL')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[600, 600], upload_to='blogs/images')),
                ('image2', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[600, 600], upload_to='blogs/images')),
                ('image3', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[600, 600], upload_to='blogs/images')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BlogComment',
            },
        ),
        migrations.CreateModel(
            name='BlogViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_user', models.CharField(blank=True, max_length=50)),
                ('views', models.IntegerField()),
                ('date_viewed', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name_plural': 'BlogViews',
            },
        ),
        migrations.CreateModel(
            name='BlogCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, max_length=150)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomment')),
                ('comment_reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BlogCommentReply',
            },
        ),
    ]
