# Generated by Django 4.1.1 on 2022-11-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='variation',
            field=models.CharField(blank=True, choices=[('blog', 'PersonalBlog'), ('service', 'Service')], default='blog', max_length=15),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'TECHNOLOGY'), ('lifestyle', 'LIFESTYLE'), ('fashion', 'FASHION'), ('art', 'ART'), ('food', 'FOOD'), ('travel', 'TRAVEL')], max_length=20),
        ),
    ]
