# Generated by Django 4.1.1 on 2022-11-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=250)),
                ('region', models.TextField(max_length=100)),
                ('age', models.CharField(choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult')], default='adult', max_length=10)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both')], default='men', max_length=10)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('white', 'White'), ('grey', 'Grey'), ('orange', 'Orange'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('black', 'Black'), ('brown', 'Brown'), ('yellow', 'Yellow')], default='black', max_length=15)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('size', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_available', models.BooleanField(default=True)),
                ('image1', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[600, 600], upload_to='product/image1')),
                ('image2', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[600, 600], upload_to='product/image2')),
                ('image3', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[600, 600], upload_to='product/image3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'product',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'subcategory',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(blank=True, max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory')),
            ],
            options={
                'verbose_name_plural': 'variation',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variation'),
        ),
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
