# Generated by Django 4.1.1 on 2022-11-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_variation_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('child', 'Child'), ('adult', 'Adult')], default='adult', max_length=10),
        ),
    ]
