# Generated by Django 4.1.1 on 2022-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered_items',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='delivered_items',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
